version: '3.4'

services:
  nginx:
    image: nginx
    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/bot.conf:/etc/nginx/conf.d/bot.conf
      - ./conf/chat.conf:/etc/nginx/conf.d/chat.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
#      - ./conf/proxy.conf:/etc/nginx/proxy.conf
      - ./logs:/etc/nginx/logs
      - ./ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    
#    network_mode: 'host'
#    command: [nginx-debug, '-g', 'daemon off;']
